# Generated by Django 5.2 on 2025-04-26 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dose', '0002_rename_dosages_medicine_dosage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='end_date',
        ),
        migrations.AddField(
            model_name='medicine',
            name='duration_type',
            field=models.CharField(choices=[('days', 'Days'), ('months', 'Months')], default='days', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='duration_value',
            field=models.PositiveIntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('twice', 'Twice a day'), ('thrice', 'Thrice a day'), ('weekly', 'Weekly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
